adr/sprint-board-workflow.md
=> Define when to use each column in our sprint board

internal/glossary.md
Additionally fix some markdown stuff.
Closes Gamify-IT/issues#17.
=> add definitions needed in issue 17

dev-manuals/services/overworld/database-model-and-type.md
=> Define database type and data model for overworld

dev-manuals/services/overworld/database-model-and-type.md
Fixes Gamify-IT/issues#23
- Removed NoSQL database when we need to update often (PostgreSQL is also fast enough)
- Note added to use ORM
=> Change overworld database concept from review

dev-manuals/languages/java/README.md, dev-manuals/languages/java/code-format.md, dev-manuals/languages/java/lombok.md, dev-manuals/languages/java/mapping-objects.md
=> Add tools for java

dev-manuals/languages/java/README.md, dev-manuals/languages/java/code-format.md, dev-manuals/languages/java/lombok.md, dev-manuals/languages/java/mapping-objects.md, dev-manuals/languages/java/springdoc.md
=> Document how to use springdoc-openapi

dev-manuals/index.rst, dev-manuals/test-data-management/README.md
=> add guide for test data management (Gamify-IT/issues#200)

dev-manuals/test-plans/minigames/crosswordpuzzle-frontend/plans/u-crosswordpuzzle-1-start-page.md, dev-manuals/test-plans/minigames/crosswordpuzzle-frontend/plans/u-crosswordpuzzle-2-start-game.md, dev-manuals/test-plans/minigames/crosswordpuzzle-frontend/plans/u-crosswordpuzzle-3-finish-game.md, dev-manuals/test-plans/minigames/crosswordpuzzle-frontend/plans/u-crosswordpuzzle-4-restart-game.md
Closes https://github.com/Gamify-IT/issues/issues/179
=> add testplans for crosswordpuzzle

dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-16-delete-course.md
=> Add testplan for course deletion

dev-manuals/languages/java/backend-to-backend-communication.md
Closes https://github.com/Gamify-IT/issues/issues/224.
=> Document backend-to-backend communication in spring boot

dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-17-minigames-maps.md, dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-18-npcs-maps.md, dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-19-dungeons-maps.md
Closes Gamify-IT/issues#218
Closes Gamify-IT/issues#220
=> Add NPC, minigame, and dungeon spot map test plans

dev-manuals/architecture/bugfinder/README.md
=> Document bugfinder architecture

dev-manuals/test-plans/minigames/finite-quiz/u-finite-quiz-1-playthrough.md, dev-manuals/test-plans/minigames/finite-quiz/u-finitequiz-1-playthrough.md
=> Add Finite-Quiz test plans

dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-20-edit-minigame-description.md, dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-21-edit-npc-description.md
=> Add testplan for editing NPC and minigame description

dev-manuals/test-plans/overworld/u-overworld-21-area-unlocking.md
=> Add unlocking testplan

dev-manuals/authentication/authentication.md
=> document Keycloak authentication

dev-manuals/architecture/overworld-backend/README.md
Part of https://github.com/Gamify-IT/issues/issues/187
=> Document overworld backend architecture

dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-22-navigate-course-list.md, dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-23-navigate-sidebar.md, dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-24-navigate-course.md, dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-25-navigate-world.md, dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-26-navigate-minigame.md, dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-27-navigate-npc.md
Part of https://github.com/Gamify-IT/issues/issues/217
=> add test plans for lecturer interface a11y

dev-manuals/architecture/lecturer-interface/README.md
Part of https://github.com/Gamify-IT/issues/issues/187
=> Document lecturer-interface architecture

dev-manuals/architecture/overworld/README.md
=> Document overworld architecture

dev-manuals/services/integrate-new-minigame.md
=> How to integrate a new minigame

dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-29-show-books-of-area.md, dev-manuals/test-plans/lecturer-interface/u-lecturer-interface-30-edit-book-configuration.md
=> Add test plans for book configuration view

dev-manuals/architecture/chickenshock-backend/README.md, dev-manuals/architecture/chickenshock/README.md, dev-manuals/architecture/finitequiz-backend/README.md, dev-manuals/architecture/finitequiz/README.md
- add links
- add table of contents
- no diagrams added. The diagrams generated by IntelliJ were very complex and not useful.
- everything else seems to be up-to-date
Part of Gamify-IT/issues#333
=> Update chickenshock and finitequiz frontend manuals

install-manuals/minigames/bugfinder.md
=> Add bugfinder install manual

install-manuals/all-services/README.md
=> adjust hosting manual

install-manuals/overworld/overworld.md
Closes Gamify-IT/issues#344
@Gamify-IT/overworld frontend team: please add for the frontend stuff
=> Add overworld install manual

install-manuals/minigames/crosswordpuzzle.md
Closes https://github.com/Gamify-IT/issues/issues/345
=> add crosswordpuzzle install manual

protocols/statistics/2022-11-30-protocol.md
=> Add protocol about meeting for statistics

dev-manuals/achievements/achievement-types.md
=> Add achievement types documentation

adr/2022-11-30-teleporter-amount-per-area.md, adr/2022-11-30-teleporter-selection.md
This contains the ADRs for the teleporter solution
=> ADR: Where and how should teleporters be placed?

dev-manuals/test-plans/overworld/u-overworld-22-achievement-ui-category.md, dev-manuals/test-plans/overworld/u-overworld-23-achievement-ui-status.md, dev-manuals/test-plans/overworld/u-overworld-24-achievement-ui-filter.md
=> add achievements ui test plans

adr/2023-01-06-achievements.md
Added the achievements adr, which was discussed and decided a while ago, but forgotten to document
=> ADR: achievements

dev-manuals/services/integrate-new-minigame.md
Part of https://github.com/Gamify-IT/issues/issues/387.
=> Update the documentation on how to integrate a minigame

user-manuals/minigames/regexgame.md
=> Add regexgame user manual

dev-manuals/deployment/helm_chart.md, dev-manuals/deployment/kubernetes_deployment.md
=> added helm explanation
